# Lab 01

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

## Task A : Matrix Standardization

In [12]:
def normalize(X):
    mean = np.mean(X, axis = 0)
    std = np.std(X, axis = 0)
    X = (X - mean)/(std  + 1e-12)
    return X

In [13]:
X = np.random.random((4,5))
X

array([[0.64167602, 0.18527425, 0.83477723, 0.34769795, 0.95656067],
       [0.16952579, 0.80442744, 0.31748851, 0.59787589, 0.63119624],
       [0.76415867, 0.0960998 , 0.02150966, 0.3088169 , 0.48188044],
       [0.87126313, 0.2925801 , 0.45188293, 0.70549765, 0.8270097 ]])

In [14]:
normalize(X)

array([[ 0.11206663, -0.58051722,  1.46578052, -0.85348159,  1.27965431],
       [-1.65049414,  1.67548642, -0.30428915,  0.64729891, -0.51189451],
       [ 0.56930056, -0.90544146, -1.31707593, -1.08672327, -1.3340697 ],
       [ 0.96912695, -0.18952774,  0.15558456,  1.29290596,  0.5663099 ]])

## Task B : Pairwise Distances in the Plane

In [54]:
def pairwise_differences(P, Q) : 
    p = len(P) # rows =  number p points
    q = len(Q) # cols = number q points
    D = np.zeros((p,q))

    for i in range(p) : 
        for j in range(q) : 
            D[i,j] = np.sqrt(np.sum([(P[i,x] - Q[j,x])**2 for x in range(2)]))

    return D

In [100]:
def pairwise_differences_2(P, Q) : 
    P2 = (P**2).sum(axis = 1)[:, None]
    Q2 = (Q**2).sum(axis = 1)[None, :]
    # print(P2.shape)
    # print(Q2.shape)
    # print(P2)
    # print(Q2)

    D2 = P2 + Q2 - 2 * P @ Q.T
    D = np.sqrt(D2)
    return D

In [101]:
P = np.zeros((4,2))
Q = np.ones((4,2))
Q[0,0], Q[0,1] = 0, 0

print(P)
print(Q)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [102]:
pairwise_differences(P,Q)

array([[0.        , 1.41421356, 1.41421356, 1.41421356],
       [0.        , 1.41421356, 1.41421356, 1.41421356],
       [0.        , 1.41421356, 1.41421356, 1.41421356],
       [0.        , 1.41421356, 1.41421356, 1.41421356]])

In [103]:
pairwise_differences_2(P,Q)

array([[0.        , 1.41421356, 1.41421356, 1.41421356],
       [0.        , 1.41421356, 1.41421356, 1.41421356],
       [0.        , 1.41421356, 1.41421356, 1.41421356],
       [0.        , 1.41421356, 1.41421356, 1.41421356]])

## Task C : TO DO